--CREATE USER UserMask WITHOUT LOGIN;
 

DROP TABLE IF EXISTS DADOSTST.dbo.#TMP_RA1
DROP TABLE IF EXISTS DADOSTST.dbo.#TMP_RA2
DROP TABLE IF EXISTS DADOSTST.dbo.#MASKED

-- Criando a tabela temporaria #TMP_RA1
SELECT 
		'A' AS EMP, RA_MAT, RA_CC, RA_NOME, RA_EMAIL, RA_SEXO, RA_CIC, RA_ESTADO, RA_MUNICIP, RA_BAIRRO, 
		CONVERT(date, RA_ADMISSA) RA_ADMISSA, 
		REPLACE(ISNULL(CONVERT(DATE, RA_DEMISSA), ''), '1900-01-01', '') AS RA_DEMISSA, 
		RA_SALARIO
	INTO 
		#TMP_RA1
	FROM 
		DADOSTST.dbo.SRA010
	WHERE 
		D_E_L_E_T_ = ''

-- Criando a tabela temporaria #TMP_RA2

	SELECT 
		'B' AS EMP, RA_MAT, RA_CC, RA_NOME, RA_EMAIL, RA_SEXO, RA_CIC, RA_ESTADO, RA_MUNICIP, RA_BAIRRO, 
		CONVERT(date, RA_ADMISSA) RA_ADMISSA, 
		REPLACE(ISNULL(CONVERT(DATE, RA_DEMISSA), ''), '1900-01-01', '') AS RA_DEMISSA, 
		RA_SALARIO
	INTO 
		#TMP_RA2
	FROM 
		DADOSTST.dbo.SRA020
	WHERE 
		D_E_L_E_T_ = ''

-- Criando a tabela temporaria #MASKED

SELECT * INTO #MASKED
FROM #TMP_RA1

-- Inserindo Registro na tabela temporaria #MASKED

INSERT INTO #MASKED
SELECT * FROM #TMP_RA2

-- Alterando as colunas para ficar com as mascaras;

	ALTER TABLE #MASKED ALTER COLUMN RA_MAT VARCHAR(6) MASKED WITH (FUNCTION = 'partial(5,"A",0)');
	ALTER TABLE #MASKED ALTER COLUMN RA_NOME VARCHAR(30) MASKED WITH (FUNCTION = 'partial(1,"XXXXXXX",1)');
	ALTER TABLE #MASKED ALTER COLUMN RA_CIC VARCHAR(11) MASKED WITH (FUNCTION = 'partial(1,"XXXXXXX",1)');
	ALTER TABLE #MASKED ALTER COLUMN RA_BAIRRO VARCHAR(15) MASKED WITH (FUNCTION = 'partial(1,"XXXXXXX",1)');
	ALTER TABLE #MASKED ALTER COLUMN RA_SEXO VARCHAR(15) MASKED WITH (FUNCTION = 'default()');
	ALTER TABLE #MASKED ALTER COLUMN RA_EMAIL VARCHAR(50) MASKED WITH (FUNCTION = 'email()');
	ALTER TABLE #MASKED ALTER COLUMN RA_SALARIO ADD MASKED WITH (FUNCTION = 'random(1,10)');

-- Executando com usuario sem
EXECUTE AS USER = 'UserMask';  
	SELECT * FROM #MASKED;
REVERT; 

--SELECT * FROM #TMP_RA1
--SELECT * FROM #TMP_RA2